# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build and Push to ACR'
  steps:
  - task: Docker@2
    displayName: 'Build and Push Docker Image'
    inputs:
      command: 'buildAndPush'
      repository: 'yourACRName.azurecr.io/yourImageName'
      Dockerfile: '**/Dockerfile'
      tags: 'latest'

- job: Deploy
  displayName: 'Deploy to Azure App Service'
  dependsOn: Build
  steps:
  - task: AzureWebApp@1
    displayName: 'Azure Web App Deploy'
    inputs:
      azureSubscription: 'YourAzureServiceConnectionName'
      appName: 'Portfolio'
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'
